// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWThq9F78Gh3ONq-p8s4ygDls6UagfyK0',
    appId: '1:272868394669:web:ffc7d3c80011edddf4a824',
    messagingSenderId: '272868394669',
    projectId: 'assignment-3f65a',
    authDomain: 'assignment-3f65a.firebaseapp.com',
    databaseURL: 'https://assignment-3f65a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'assignment-3f65a.appspot.com',
    measurementId: 'G-SPDW6BT12V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMXXS4b9NPWyEdihR5YjjsxKHyJM4Z2Rg',
    appId: '1:272868394669:android:6bac63c294bf45eff4a824',
    messagingSenderId: '272868394669',
    projectId: 'assignment-3f65a',
    databaseURL: 'https://assignment-3f65a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'assignment-3f65a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyc5UHAUqvt2jebSdvbu32yiHvIRYgRKc',
    appId: '1:272868394669:ios:b706263216d82de4f4a824',
    messagingSenderId: '272868394669',
    projectId: 'assignment-3f65a',
    databaseURL: 'https://assignment-3f65a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'assignment-3f65a.appspot.com',
    iosBundleId: 'com.sap.bits.assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyc5UHAUqvt2jebSdvbu32yiHvIRYgRKc',
    appId: '1:272868394669:ios:b706263216d82de4f4a824',
    messagingSenderId: '272868394669',
    projectId: 'assignment-3f65a',
    databaseURL: 'https://assignment-3f65a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'assignment-3f65a.appspot.com',
    iosBundleId: 'com.sap.bits.assignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWThq9F78Gh3ONq-p8s4ygDls6UagfyK0',
    appId: '1:272868394669:web:e34aca4139a128f1f4a824',
    messagingSenderId: '272868394669',
    projectId: 'assignment-3f65a',
    authDomain: 'assignment-3f65a.firebaseapp.com',
    databaseURL: 'https://assignment-3f65a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'assignment-3f65a.appspot.com',
    measurementId: 'G-37GCGYKSJS',
  );
}
